### ISSUE TITLE
Cannot start NP2COMV.exe

### ISSUE THREAD

**Issue by Morpheus68** [albertjan/PipeToCom#14]
Hello!
A has a Windows Server 2008 R2 Standard SP1 with Hyper-V role, and Linux appliance, as guest.
In guest system i want to have access to serial port for configuration Linux appliance.
I downloaded NP2COM files and started install.
After installation Faramework 4.0 i run NP2COMV.exe and get next exception:
###### 

Title: Microsoft .NET Framework
Message:
Unhandled exception has occurred in your application. If you click Continue, the application will
ignore this error and attemp to continue. If you click Quit? the application will close immediately.

Illegal characters in path

Details:
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

*************\* Exception Text **************
System.ArgumentException: Illegal characters in path.
   at System.IO.Path.CheckInvalidPathChars(String path)
   at System.IO.Path.InternalCombine(String path1, String path2)
   at System.IO.FileSystemEnumerableIterator`1.CreateSearchResult(SearchData localSearchData, WIN32_FIND_DATA findData)
   at System.IO.FileSystemEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.IO.Directory.InternalGetFileDirectoryNames(String path, String userPathOriginal, String searchPattern, Boolean includeFiles, Boolean includeDirs, SearchOption searchOption)
   at System.IO.Directory.InternalGetFiles(String path, String searchPattern, SearchOption searchOption)
   at NP2COMV.Form1.Form1_Load(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

*************\* Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.239 (RTMGDR.030319-2300)
##     CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll

NP2COMV
    Assembly Version: 1.0.0.0
    Win32 Version: 1.0.0.0
##     CodeBase: file:///D:/Distrib/Hyper-V/vCOM%20port/NamedPipe2Com/NP2COMV.exe

System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.235 built by: RTMGDR
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll

System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.258 built by: RTMGDR
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll

System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 built by: RTMRel
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll

Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 built by: RTMRel
##     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll

log4net
    Assembly Version: 1.2.10.0
    Win32 Version: 1.2.10.0
##     CodeBase: file:///D:/Distrib/Hyper-V/vCOM%20port/NamedPipe2Com/log4net.DLL

*************\* JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
###### 

If click Continue, form is open, but all select box is empty.

What to do?
Thank you!

**Comment by snikul** [comment]
Hello! I have exactly the same story. It was ok at first. Everything. But now NP2COMService is working ok and the data goes from esp32 to host-w10pro and then to ubuntu 16.04-minicom. But when I want to start NP2COMV...the program gives me the above mentioned otput. Help me, pl.

**Comment by albertjan** [comment]
yeah some programs open named pipes with weird characters that breaks the tool. But you should be able to change any settings you want by editing the file instead of using the np2comv.

**Comment by snikul** [comment]
Thank you so much for the reply. It was ok with NP2COMV and NP2COMService
after I initially installed the pascage. But then something happend. I just
happend to start NP2COM.exe XML Configuration file instead of NP2COMV and
in Control Panel/Programs/Delete Program Repaired Insalation of all the
FrameNetwork modules 4.5, 4.5.1..4.6.. , see the attachment file. Could it
be the problem. The name of ununtu VM port is 'comport' like in the manual.

I can edit a n2c file of course but I would like to use NP2COMV as I used
it before when I installed the service.

One more remark. In Repaired modules.png you can see .NET Framework modules
installed. There are also Russian versions of them installed (4.5.1 and
4.5.2)

Regards.

2017-10-06 12:24 GMT+03:00 Albert-Jan Nijburg <notifications@github.com>:

**Comment by snikul** [comment]
Dear Sir,

I have to apply for your assistanse again. Could you help me, please.

It was ok with NP2ComService. The service could start and run in the
automatic mode but yesterday it stuck - all the way with status: starting.
I can see status:starting
even if I switch the service off in it's properties. Starting and switched
off statuses simultaneously. You can see it in the picture attached.

I tried to reinstall the service in Admin mode with the command:c:\windows\
microsoft.net\framework\v4.0.30319\installutil.exe -t C:\NP2COM\NP2COMS.exe
but it refused with the message that the service is already installed.

How to repair or reinstall the service.

Waiting for your friendly advice.

Best Regards
Sergei Nikulin
Kaliningrad/Russia


2017-10-06 22:38 GMT+03:00 Sergey Nikulin <serg.nikulin@gmail.com>:
