### ISSUE TITLE
Win Srv 2k12 service cannot be installed and will not show up in services.msc

### ISSUE THREAD

**Issue by mmry91** [albertjan/PipeToCom#30]
Hi there, 

thanks at first for providing this awesome tool ! 

I downloaded the binary files and installted .net Framework 4.0 on my host. It's Win Srv 2k12 Standart R2 - now im trying to setup NP2COM but i could not figure out how to solve my problems ... at first I cleand the downloaded files with streams /s /d in my folder. Then typed into run the installation command .. everytime one thing will be logged.. see the following.. now I've got no idea anymore - sorry for my bad english... :D hopefully you can give me a hint ( sorry for german log). 

Thanks in advance,

mmry

Dienst NP2COMService wird installiert...
Die EventLog-Quelle NP2COMService im Protokoll Application wird erstellt...
Assembly D:\Images\np2com\NP2COMS.exe wird zurückgesetzt.
Betroffene Parameter:
   logtoconsole = 
   t = 
   logfile = D:\Images\np2com\NP2COMS.InstallLog
   assemblypath = D:\Images\np2com\NP2COMS.exe
Der vorherige Zustand des Ereignisprotokolls für die Quelle NP2COMService wird wiederhergestellt.

**Comment by agacovski** [comment]
Hi mmry,

I managed to install the service yesterday on a 2012 R2 server. The workaround it to manually add the service using the sc command.

My install path is c:\NP2COM\

// This is the work around. Any exceptions NP2COMS throws is logged in the windows event viewer
sc create "NP2COMService" binpath="c:\NP2COM\NP2COMS.exe" start=auto displayname="NP2COMService"

I use NP2COMS to pass through a serial to a VM running windows 8.1 64bit with Davis weather link software. The only issue is if the vm is shutdown or rebooted then you would have to also restart the NP2COMService as I suspect the handle for the pipe the VM creates changes.

Hope this helps.

Cheers,
Alex
