### ISSUE TITLE
RTS/CTS issue

### ISSUE THREAD

**Issue by brenton84** [albertjan/PipeToCom#31]
Hi Albert,

I have a similar issue to that described in https://github.com/albertjan/PipeToCom/issues/6 where the door pin software appears to use RTS/CTS so it won't connect. I have no issues when I test the com port pass-through with a Cisco router via  HyperTerminal. I know you talked about the possibility of a kernel hack to get it to work, can you shed some more light on this?

Thanks,

Brenton

**Comment by albertjan** [comment]
Oh man I don't know what I meant with "kernel hack" 4 years ago. I sincerely hope I didn't mean "kernel hack". 

That being said, the most feasible way of getting rts/cts to work in np2com would be to add a virtual comport on the host and connect to that encode the on and off messages in a protocol. This would be a **lot** of work. 

I think you'll have better luck if you look at com0com's com2tcp and hook that up I think they implemented the above. 

I don't have the time to add this feature to NP2COM I'm sorry.
