### ISSUE TITLE
Service stops when USB Serial device is unplugged

### ISSUE THREAD

**Issue by mcmlxxix** [albertjan/PipeToCom#32]
Hi there. I appreciate this little piece of software you have created, and it is the only solution that actually works that I've found so far (I'm connecting an old Allen Bradley PLC to a dedicated VM via USB-Serial cable). The problem I'm having is that in the course of normal use, the cable may be unplugged and plugged back in several times, switched off and on, etc.. would it be possible to let the service continue running despite the com port disappearing? (it's COM3, so it drops off the device list if unplugged)

**Comment by albertjan** [comment]
You could but it'd require a part rewrite of the code. Because I never even thought about disappearing com ports when I wrote it. :smile: You'd have to gracefully stop the threads that read and write to the comport and namedpipe and then, somehow keep tabs on com ports and when a new one appears try to restart the threads again.

But out of the box it doesn't work. (You might be able to cobble together a smart powerhell script to do it)

**Comment by mcmlxxix** [comment]
I grabbed the source, and will see if I can make it happen. Just want to see if an exception is being thrown when the com port disappears, because that would be a handy place to stop the threads as you mentioned, and maybe periodically attempt to restart them (again catching exceptions)

**Comment by albertjan** [comment]
@mcmlxxix I'm sure there's an exception. Otherwise the service wouldn't stop, I bet you can find it in the windows event log. If you need some tips let me know.

**Comment by mcmlxxix** [comment]
Ok. So I've pretty much ripped everything out of the service and put it into the NP2COMV configuration GUI (I wanted this to be a GUI application and not a service anyway, so this was a convenient place to do that). Everything is working, and it no longer crashes if I make the COM port disappear, and it wont crash or do anything unpleasant if I attempt to start the COM -> NP proxy when either the COM port does not exist or the VM has not been started (Named Pipe doesn't exist).. the only issue remaining is that I'm having a hard time monitoring the status of the proxy (or proxies) from the parent thread, as the vast majority of thrown exceptions occur within the child Connection() thread, and I want to be able to start/stop from the GUI if something goes wrong. I'm sure I'll find what I need with some googling, but I figured I'd let you know what I've done with it so far.

**Comment by albertjan** [comment]
Haha good job :) glad you found it usefull. Could you share the code?

**Comment by mcmlxxix** [comment]
https://github.com/mcmlxxix/PipeToCom
Seems to be working nicely.. let me know if you try it and notice anything funny going on..

**Comment by mcmlxxix** [comment]
Unfortunately I hacked the code apart so much that implementing the changes I made aren't so straightforward, but I will close this issue anyway as it's been quite a while. Feel free to borrow from my code if you want to make any changes to your copy. I will probably be updating it to use the .NET 4.5+ Stream.AsyncRead/AsyncWrite  methods in the near future.
