### ISSUE TITLE
Can I use NP2COM for two com ports

### ISSUE THREAD

**Issue by ccurtis1** [albertjan/PipeToCom#33]
I need to map 2 serial ports from the VM Host to the VM Guest.
Can I do this with 2 configuration files, or a single file with two sections?
Is it even possible?

**Comment by albertjan** [comment]
Yeah you can just add them to the config file

**Comment by ccurtis1** [comment]
Would I format it like

``` xml
<Settings>
Com1 settings
</Settings>
<Settings>
Com2 settings
</Settings>
```

or

``` xml
<Settings>
Com1 settings
Com2 settings
</Settings>
```

**Comment by albertjan** [comment]
Oh sorry I mean you can just add another `n2c` file.

**Comment by albertjan** [comment]
https://github.com/albertjan/PipeToCom/blob/master/NP2COMS/NP2COMService.cs#L34 here is where it happens

**Comment by ccurtis1** [comment]
Perfect I will test tonight!
