### ISSUE TITLE
Multiple connections?

### ISSUE THREAD

**Issue by tas7154** [albertjan/PipeToCom#34]
Don't know if you are still answering questions about this or not. I have been using this for almost 2 years without a problem. But an interesting situation came up today. I have a 4 port serial card and was wondering if there is a way to create a separate connection for each one i.e. COM1 to \.\pipe\con1 COM 3 to \.\pipe\con3 and so on. It only seems to allow one connection at a time but I was wondering if there was a way to connect multiple devices at the same time.

**Comment by albertjan** [comment]
You can just add more `.n2c` files. 😄

**Comment by albertjan** [comment]
Glad you're having fun with it.

**Comment by tas7154** [comment]
That is what I thought and what I did but it seemed that only one connection worked at a time.

**Comment by tas7154** [comment]
Oh and yeah I am loving it. Thanks for creating it.

**Comment by tas7154** [comment]
I feel so silly I just forgot to run as administrator. Works great! Thanks again,

**Comment by albertjan** [comment]
Awesome! :)
