### ISSUE TITLE
"Com Port" doesn't show up on Windows Terminal Server

### ISSUE THREAD

**Issue by matze19999** [albertjan/PipeToCom#37]
As you can see, the option "Com Port 1" doensn't show up in HyperV-Manager for all our windows terminal server.
On all other server, the option is available.

![unbenannt](https://user-images.githubusercontent.com/13684520/40218374-423d8a9a-5a71-11e8-92fc-4d0a740f3355.png)

**Comment by matze19999** [comment]
Update; The option won't show up on all Server 2016 machines.

**Comment by meluvalli** [comment]
FYI, you have to use generation 1.  Can't be a GEN 2 Hyper-V.
